### ISSUE TITLE
Add compatibility to GreaseMonkey 4.x

### ISSUE THREAD

**Issue by FlandreDaisuki** [FlandreDaisuki/rollup-plugin-userscript-metablock#1]
Maybe check transformed code and print warning or throw Error if use `@grant GM.*` but found `GM_*` in code or vice versa.

Maybe transform code and add `@grant` both API and append [GMC](https://github.com/StigNygaard/GMCommonAPI.js) or [gm4-polyfill](https://github.com/greasemonkey/gm4-polyfill) to `@require`. ( I think this very hard and maybe not metablock plugin do... )

**Comment by nikolay-borzov** [comment]
`@grant` check is done by [eslint-plugin-userscripts](https://github.com/Yash-Singh1/eslint-plugin-userscripts) [`compat-grant`](https://github.com/Yash-Singh1/eslint-plugin-userscripts/blob/main/docs/rules/compat-grant.md) rule

**Comment by FlandreDaisuki** [comment]
WOW!! I've never thought that using the eslint plugin to validate it. Good work!
