### ISSUE TITLE
Meta key `@sandbox`

### ISSUE THREAD

**Issue by cvzi** [FlandreDaisuki/rollup-plugin-userscript-metablock#26]
Tampermonkey supports a new meta key `@sandbox`
It can have three values:
 - `raw`
 - `JavaScript`
 - `DOM`

See https://www.tampermonkey.net/documentation.php#meta:sandbox

**Comment by FlandreDaisuki** [comment]
Thanks for the information. I'll review these monkeys new meta keys recently.

**Comment by cvzi** [comment]
Thanks for the quick fix!
