### ISSUE TITLE
允許手動傳入 metablock 的物件?

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/rollup-plugin-userscript-metablock#4]
如題，像是下面可以直接傳入而不是一定得指定一個檔案
```js
metablock({
  meta: {
    name: 'xxx',
    description: 'yyy',
    // etc...
  },
  order: ['name', 'description', 'namespace', '...', 'grant'],
  version: null
}
```

**Comment by FlandreDaisuki** [comment]
如果同時有的話呢？誰覆寫誰或忽略誰？

**Comment by maple3142** [comment]
我認為 `meta` 的優先級應該要比 `file` 高
希望有這個的原因是因為想把 `meta.json` 和 `package.json` 合在一起

**Comment by FlandreDaisuki** [comment]
我覺得可以，不過其實整個專案我想全部打掉重練

你可以先送 patch 跟 test 進來我可以馬上 publish 上去

**Comment by maple3142** [comment]
如果要打掉重練的話我覺得可以增加一些直接讀取 `package.json` 的功能，然後刪除一些不必要的 key 弄成 metablock

**Comment by FlandreDaisuki** [comment]
**dependencies** 很難
**name**, **description**, **license**, **version**, **author** 這些感覺可以
**supportURL** 感覺可以用 `package.json` 的 **bugs.url** 或 **homepage**

感覺可以作為選項

**Comment by FlandreDaisuki** [comment]
有些沒有 release 到 npm 就沒有 unpkg，你也不能確定 unpkg 的依賴人家放在哪 (`dist/`, `build/`, `export/`)跟哪種依賴 (`.min.js`, `.js`, `.slim.js`)
然後可能該 `package.json` 可能是某個大專案的，輸出成 userscript 只是順便的功能，這樣就很麻煩

所以我傾向不主動處理 `dependencies`，交給 build script 去組成並丟給 custom `meta`

**Comment by FlandreDaisuki** [comment]
Solved by #6
